### ISSUE TITLE
TypeError: reset() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by meghbhalerao** [TUMcps/human-robot-gym#12]
Hi, I am running the following bash command - 
```shell 
bash human_robot_gym/training/icra_2024_environment_evaluation.sh R HumanReach 100 1000000 100 8 800
```
which in-turn runs the following python command - 
```shell
python human_robot_gym/training/create_expert_dataset.py -cp config_icra_2024/environment_evaluation/dataset_creation -cn R dataset_name=HumanReach n_episodes=100 environment.horizon=100 environment.verbose=False
```

but I get the following error - below is the full error - 

```shell
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Error executing job with overrides: ['dataset_name=HumanReach', 'n_episodes=100', 'environment.horizon=100', 'environment.verbose=False']
Traceback (most recent call last):
  File "human_robot_gym/training/create_expert_dataset.py", line 373, in <module>
    main()
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "human_robot_gym/training/create_expert_dataset.py", line 355, in main
    collect_data(
  File "human_robot_gym/training/create_expert_dataset.py", line 208, in collect_data
    obs = env.reset()
  File "/home/mb230/projects/human-robot-gym/human_robot_gym/wrappers/dataset_collection_wrapper.py", line 177, in reset
    obs = super().reset()
  File "/home/mb230/anaconda3/envs/hrgym/lib/python3.8/site-packages/gym/core.py", line 303, in reset
    return self.env.reset(seed=seed, **kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
```

My gym and stable baseline versions are as follows - 
```shell 
pip freeze | grep stable && pip freeze | grep gym
stable-baselines3==1.5.0
gym @ git+https://github.com/openai/gym.git@9180d12e1b66e7e2a1a622614f787a6ec147ac40
gym-notices==0.0.8
-e git+ssh://git@github.com/meghbhalerao/human-robot-gym.git@da7823a1731a96cab7c8a1f4f88b374e7acad407#egg=human_robot_gym
```
I have pip installed gym from the fixed typo in the commit hash as you suggested in https://github.com/TUMcps/human-robot-gym/issues/11#issuecomment-2485895052

I tried googling the issue -
1. https://github.com/openai/gym/issues/2531
2. https://stackoverflow.com/questions/76509663/typeerror-joypadspace-reset-got-an-unexpected-keyword-argument-seed-when-i

but many of them say it is an internal bug in gym and seems to be fixed in the latest version, but we are not using the latest gym version, but rather a specifc version. 

Am I missing something here? Also, the error is stemming from inside the gym library so it seems to be something to do with the versioning etc, so I am not sure how to go about fixing this.

It would be great to know some suggestions regarding how to handle this ... thank you so much again!

**Comment by meghbhalerao** [comment]
Edit - this is fixed after uninstalling gym (which was installed using the commit hash as recommended in https://github.com/TUMcps/human-robot-gym/issues/11#issuecomment-2485895052) and reinstalling it using - 
` pip install setuptools==65.5.1 pip==21 wheel==0.38.0` followed by 
`pip install gym==0.21.0`

I think this is what is orginally recommended according to the environment.yml file, but maybe I was missing something earlier which caused my issue in the first place, but in any case, the above commands fixed my issue.
