### ISSUE TITLE
have error to run demo file

### ISSUE THREAD

**Issue by Moj79a** [TUMcps/human-robot-gym#15]
hi. how can i solve this error:
`python human_robot_gym/demos/demo_reach_human_environment.py`
Traceback (most recent call last):
  File "human_robot_gym/demos/demo_reach_human_environment.py", line 18, in <module>
    from human_robot_gym.demonstrations.experts import ReachHumanExpert
  File "/home/user/human-robot-gym/human_robot_gym/__init__.py", line 6, in <module>
    from human_robot_gym.controllers.failsafe_controller.failsafe_controller import (
  File "/home/user/human-robot-gym/human_robot_gym/controllers/failsafe_controller/failsafe_controller/__init__.py", line 5, in <module>
    import safety_shield_py  # noqa: F401
ModuleNotFoundError: No module named 'safety_shield_py'

**Comment by JakobThumm** [comment]
It seems like you haven't installed the safety shield.
https://github.com/TUMcps/human-robot-gym?tab=readme-ov-file#install-the-failsafe-controller--safety-shield

**Comment by LittlePotatoChip** [comment]
> It seems like you haven't installed the safety shield. https://github.com/TUMcps/human-robot-gym?tab=readme-ov-file#install-the-failsafe-controller--safety-shield

but I have install the safety shield,same error

**Comment by LittlePotatoChip** [comment]
tried this,manual install safety_shield_py individually.
[https://github.com/JakobThumm/sara-shield](url)
